local Players=game:GetService("Players");local ReplicatedStorage=game:GetService("ReplicatedStorage");local Workspace=game:GetService("Workspace");local RunService=game:GetService("RunService");local TweenService=game:GetService("TweenService");local StarterGui=game:GetService("StarterGui");local LocalPlayer=Players.LocalPlayer
local function safeFindPath(root,...)local cur=root;for i=1,select("#",...)do if typeof(cur)~="Instance"then return nil end;local name=select(i,...);if typeof(name)~="string"then name=tostring(name or "")end;local nextCur;local ok=pcall(function()nextCur=cur:FindFirstChild(name)end);if(not ok)or(nextCur==nil)then return nil end;cur=nextCur end;return cur end
local function dist(a,b)return(a-b).Magnitude end;local function startsWithIC(s,p)s,p=tostring(s or ""):lower(),tostring(p or ""):lower()return s:sub(1,#p)==p end
local enemiesRoot,specialEnemiesRoot,questsRoot,chestsRoot,fruitRoot,spawnPointsRoot
local function firstExisting(...)for i=1,select("#",...)do local v=select(i,...);if typeof(v)=="Instance"then return v end end;return nil end
local function refreshRoots()local p=Workspace:FindFirstChild("Playability");local pEnemies=p and(p:FindFirstChild("Enemys")or p:FindFirstChild("Enemies"))or nil;local iEnemies=safeFindPath(Workspace,"IgnoreList","Int","NPCs","Enemys")or safeFindPath(Workspace,"IgnoreList","Int","NPCs","Enemies");enemiesRoot=firstExisting(pEnemies,iEnemies);local pSpecial=p and(p:FindFirstChild("SpecialEnemys")or p:FindFirstChild("SpecialEnemies"))or nil;specialEnemiesRoot=firstExisting(pSpecial);local q1=safeFindPath(Workspace,"IgnoreList","Int","NPCs","Quests");local q2=safeFindPath(Workspace,"IgnoreList","Int","Quests");questsRoot=firstExisting(q1,q2);chestsRoot=firstExisting(safeFindPath(Workspace,"IgnoreList","Int","Chests"));fruitRoot=firstExisting(safeFindPath(Workspace,"IgnoreList","Data","FruitSpawns"));local sp1=safeFindPath(Workspace,"IgnoreList","Int","NPCs","SpawnPoint");local sp2=safeFindPath(Workspace,"IgnoreList","Int","SpawnPoint");local sp3=safeFindPath(Workspace,"IgnoreList","Int","NPCs");spawnPointsRoot=firstExisting(sp1,sp2,sp3)end;refreshRoots()
local function resolveToolsEvent()local bs=ReplicatedStorage:FindFirstChild("BetweenSides");if not bs then return nil end;local rem=bs:FindFirstChild("Remotes");if not rem then return nil end;local evs=rem:FindFirstChild("Events");if not evs then return nil end;return evs:FindFirstChild("ToolsEvent")or evs:FindFirstChild("ToolEvent")end
local function teleportToCFrame(cf)local char=LocalPlayer.Character or LocalPlayer.CharacterAdded:Wait();local hrp=char:FindFirstChild("HumanoidRootPart");local hum=char:FindFirstChildOfClass("Humanoid");if not(hrp and hum and cf)then return end;local target=cf.Position+Vector3.new(0,5,0);local tw=TweenService:Create(hrp,TweenInfo.new(0.3,Enum.EasingStyle.Quad,Enum.EasingDirection.Out),{CFrame=CFrame.new(target)});tw:Play();tw.Completed:Wait();if dist(hrp.Position,target)>12 then hum:MoveTo(cf.Position)end end
local function tryActivatePrompt(prompt)if not prompt then return false end;local ok=false;pcall(function()prompt:InputHoldBegin();local d=prompt.HoldDuration or 0;if d>0 then task.wait(d+0.1)end;prompt:InputHoldEnd();ok=true end);return ok end
local function tryAcceptDialog()local g=LocalPlayer:FindFirstChild("PlayerGui");if not g then return false end;for _,gui in ipairs(g:GetDescendants())do if gui:IsA("GuiButton")then local t=(gui.Text or ""):lower();if t:find("accept")or t:find("aceitar")or t:find("yes")or t:find("ok")then pcall(function()gui:Activate()end)return true end end end;return false end
local function tryAttack()local ev=resolveToolsEvent();if ev and ev.FireServer then pcall(function()ev:FireServer("Effects",1)end)end end
local function findClosestEnemy(baseName,fromPos)local roots,best,bestD={},nil,nil;if enemiesRoot then roots[#roots+1]=enemiesRoot end;if specialEnemiesRoot then roots[#roots+1]=specialEnemiesRoot end;for _,root in ipairs(roots)do for _,area in ipairs(root:GetChildren())do for _,obj in ipairs(area:GetChildren())do if obj:IsA("Model")and startsWithIC(obj.Name,baseName)then local hr=obj:FindFirstChild("HumanoidRootPart")or obj.PrimaryPart;local hum=obj:FindFirstChild("Humanoid");if hr and hum and hum.Health>0 then local d=dist(hr.Position,fromPos);if(not bestD)or d<bestD then best,bestD=obj,d end end end end end end;return best end
local function findClosestQuestNPC(pattern,fromPos)if not questsRoot then return nil end;local pat=tostring(pattern or ""):lower();local best,bestD;for _,area in ipairs(questsRoot:GetChildren())do for _,npc in ipairs(area:GetChildren())do if npc:IsA("Model")and tostring(npc.Name):lower():find(pat,1,true)then local hr=npc:FindFirstChild("HumanoidRootPart")or npc.PrimaryPart;if hr then local d=dist(hr.Position,fromPos);if(not bestD)or d<bestD then best,bestD=npc,d end end end end end;return best end
local function findClosestPartDesc(root,fromPos,nameFilter)if not root then return nil end;local nf=nameFilter and nameFilter:lower()or nil;local best,bestD,bestNode;for _,d in ipairs(root:GetDescendants())do local part=d:IsA("BasePart")and d or d:FindFirstChildWhichIsA("BasePart");if part then if not nf or tostring(d.Name):lower():find(nf,1,true)then local dd=dist(part.Position,fromPos);if(not bestD)or dd<bestD then best,bestD,bestNode=part,dd,d end end end end;return bestNode end
local function findClosestChest(fromPos)return findClosestPartDesc(chestsRoot,fromPos,nil)end
local function findClosestFruit(fromPos,nameFilter)local fruit=findClosestPartDesc(fruitRoot,fromPos,nameFilter);if fruit then return fruit end;local dropped=safeFindPath(Workspace,"Playability","DroppedTools");return dropped and findClosestPartDesc(dropped,fromPos,nameFilter)or nil end
local ENEMY_PREFIX_OVERRIDES={["bandits hunter"]="Bandit",["bandit hunter"]="Bandit"}
local function enemyPrefixFromNpcName(npcName)local n=tostring(npcName or ""):lower();if ENEMY_PREFIX_OVERRIDES[n]then return ENEMY_PREFIX_OVERRIDES[n]end;n=n:gsub("hunters?",""):gsub("boss",""):gsub("quest","");n=n:gsub("%p",""):gsub("%s+"," "):gsub("^%s*(.-)%s*$","%1");if #n==0 then return"Bandit"end;if n:sub(-1)=="s"then n=n:sub(1,-2)end;local parts={};for w in n:gmatch("%S+")do parts[#parts+1]=w:sub(1,1):upper()..w:sub(2)end;return table.concat(parts," ")end
local function getNextQuestText()local g=LocalPlayer:FindFirstChild("PlayerGui");if not g then return nil end;local node=safeFindPath(g,"MainUI","AnotherMenus","TrackerFrame","NextQuest");if node and(node:IsA("TextLabel")or node:IsA("TextButton"))then local t=tostring(node.Text or "");return(#t>0)and t or nil end;return nil end
local function findNpcByFuzzyText(txt)if not questsRoot or not txt then return nil end;local low=txt:lower();local best,score=nil,0;for _,area in ipairs(questsRoot:GetChildren())do for _,npc in ipairs(area:GetChildren())do if npc:IsA("Model")then local n=tostring(npc.Name):lower();if low:find(n,1,true)then local s=#n;if s>score then best,score=npc,s end end end end end;return best end
local autoQuest,autoChest,autoFruit=false,false,false;local autoByLevel=true;local questPattern="bandits hunter";local enemyBaseName="Bandit";local fruitNameFilter=nil
local function updateAutoFarmTargets()local txt=getNextQuestText();if txt then local npcModel=findNpcByFuzzyText(txt);if npcModel then questPattern=tostring(npcModel.Name);enemyBaseName=enemyPrefixFromNpcName(questPattern);return true end end;local char=LocalPlayer.Character;local hrp=char and char:FindFirstChild("HumanoidRootPart");if hrp then local npc=findClosestQuestNPC("",hrp.Position);if npc then questPattern=tostring(npc.Name);enemyBaseName=enemyPrefixFromNpcName(questPattern);return true end end;return false end
task.spawn(function()while true do local char=LocalPlayer.Character;local hrp=char and char:FindFirstChild("HumanoidRootPart");if hrp then if autoQuest then if autoByLevel then updateAutoFarmTargets()end;local npc=findClosestQuestNPC(questPattern,hrp.Position);if npc then local part=npc:FindFirstChild("HumanoidRootPart")or npc.PrimaryPart;if part then teleportToCFrame(part.CFrame);task.wait(0.45);local prompt=npc:FindFirstChildOfClass("ProximityPrompt")or npc:FindFirstChild("ProximityPrompt",true);if prompt then tryActivatePrompt(prompt)end;task.wait(0.45);tryAcceptDialog();task.wait(0.55);local enemy=findClosestEnemy(enemyBaseName,hrp.Position);if enemy then local ehrp=enemy:FindFirstChild("HumanoidRootPart")or enemy.PrimaryPart;if ehrp then teleportToCFrame(ehrp.CFrame);local t0=tick();while autoQuest and enemy and enemy:FindFirstChild("Humanoid")and enemy.Humanoid.Health>0 and(tick()-t0)<30 do tryAttack();task.wait(0.25)end end end end end end;if autoChest then local chest=findClosestChest(hrp.Position);if chest then local part=chest:IsA("BasePart")and chest or chest:FindFirstChildWhichIsA("BasePart");if part then teleportToCFrame(part.CFrame);task.wait(0.35);local prompt=chest:FindFirstChildOfClass("ProximityPrompt")or part:FindFirstChildOfClass("ProximityPrompt");if prompt then tryActivatePrompt(prompt)end end end end;if autoFruit then local node=findClosestFruit(hrp.Position,fruitNameFilter);if node then local part=node:IsA("BasePart")and node or node:FindFirstChildWhichIsA("BasePart");if part then teleportToCFrame(part.CFrame);task.wait(0.45);local prompt=node:FindFirstChildOfClass("ProximityPrompt")or part:FindFirstChildOfClass("ProximityPrompt");if prompt then tryActivatePrompt(prompt)end end end end end;task.wait(0.6)end end)
local playerGui=LocalPlayer:WaitForChild("PlayerGui");local screenGui=Instance.new("ScreenGui");screenGui.Name="VoxSeasHub";screenGui.IgnoreGuiInset=true;screenGui.ResetOnSpawn=false;screenGui.ZIndexBehavior=Enum.ZIndexBehavior.Sibling;screenGui.DisplayOrder=1000;screenGui.Parent=playerGui
local function mkCorner(i,r)local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,r or 10);c.Parent=i end;local function mkStroke(i,t,tr)local s=Instance.new("UIStroke");s.Thickness=t or 1;s.Transparency=tr or 0.8;s.Parent=i end
local menuBtn=Instance.new("TextButton");menuBtn.Name="MenuBtn";menuBtn.Text="☰";menuBtn.AnchorPoint=Vector2.new(0,0.5);menuBtn.Position=UDim2.new(0,12,0.5,-32);menuBtn.Size=UDim2.new(0,56,0,56);menuBtn.AutoButtonColor=true;menuBtn.TextScaled=true;menuBtn.BackgroundColor3=Color3.fromRGB(32,32,32);menuBtn.TextColor3=Color3.new(1,1,1);menuBtn.ZIndex=20;menuBtn.Parent=screenGui;mkCorner(menuBtn,12);mkStroke(menuBtn,1,0.8)
local mainFrame=Instance.new("Frame");mainFrame.Name="MainFrame";mainFrame.AnchorPoint=Vector2.new(0,0.5);mainFrame.Position=UDim2.new(0,84,0.5,-160);mainFrame.Size=UDim2.new(0,300,0,360);mainFrame.BackgroundColor3=Color3.fromRGB(18,18,18);mainFrame.BackgroundTransparency=0.25;mainFrame.BorderSizePixel=0;mainFrame.Visible=false;mainFrame.ZIndex=15;mainFrame.Parent=screenGui;mkCorner(mainFrame,16);mkStroke(mainFrame,1,0.85)
local header=Instance.new("Frame");header.Name="Header";header.Size=UDim2.new(1,0,0,36);header.BackgroundTransparency=1;header.ZIndex=16;header.Parent=mainFrame
local title=Instance.new("TextLabel");title.BackgroundTransparency=1;title.Size=UDim2.new(1,-36,1,0);title.Position=UDim2.new(0,10,0,0);title.Text="VoxSeas Hub";title.TextXAlignment=Enum.TextXAlignment.Left;title.TextColor3=Color3.fromRGB(230,230,230);title.TextScaled=true;title.ZIndex=16;title.Parent=header
local closeBtn=Instance.new("TextButton");closeBtn.Text="×";closeBtn.Size=UDim2.new(0,28,0,28);closeBtn.Position=UDim2.new(1,-32,0,4);closeBtn.BackgroundTransparency=0.3;closeBtn.BackgroundColor3=Color3.fromRGB(40,40,40);closeBtn.TextColor3=Color3.fromRGB(255,255,255);closeBtn.TextScaled=true;closeBtn.ZIndex=16;closeBtn.Parent=header;mkCorner(closeBtn,20)
local tabsBar=Instance.new("Frame");tabsBar.Size=UDim2.new(1,-16,0,34);tabsBar.Position=UDim2.new(0,8,0,40);tabsBar.BackgroundTransparency=0.3;tabsBar.BackgroundColor3=Color3.fromRGB(24,24,24);tabsBar.ZIndex=15;tabsBar.Parent=mainFrame;mkCorner(tabsBar,10)
local content=Instance.new("Frame");content.Size=UDim2.new(1,-16,1,-90);content.Position=UDim2.new(0,8,0,80);content.BackgroundTransparency=1;content.ZIndex=14;content.Parent=mainFrame
local tabs={}
local function createTab(t,i,total)local btn=Instance.new("TextButton");btn.Size=UDim2.new(1/total,-4,1,-4);btn.Position=UDim2.new((i-1)/total,(i-1)*2,0,2);btn.BackgroundColor3=Color3.fromRGB(50,50,50);btn.BackgroundTransparency=0.2;btn.Text=t;btn.TextScaled=true;btn.TextColor3=Color3.fromRGB(255,255,255);btn.AutoButtonColor=true;btn.ZIndex=16;btn.Parent=tabsBar;mkCorner(btn,8);local frame=Instance.new("ScrollingFrame");frame.Size=UDim2.new(1,0,1,0);frame.BackgroundTransparency=1;frame.ScrollBarThickness=6;frame.AutomaticCanvasSize=Enum.AutomaticSize.Y;frame.Visible=false;frame.ZIndex=14;frame.Parent=content;local pad=Instance.new("UIPadding");pad.PaddingTop=UDim.new(0,8);pad.PaddingLeft=UDim.new(0,6);pad.PaddingRight=UDim.new(0,6);pad.Parent=frame;local lay=Instance.new("UIListLayout");lay.Padding=UDim.new(0,8);lay.HorizontalAlignment=Enum.HorizontalAlignment.Center;lay.SortOrder=Enum.SortOrder.LayoutOrder;lay.Parent=frame;table.insert(tabs,{button=btn,frame=frame});return btn,frame end
local farmBtn,farmFrame=createTab("Farm",1,2);local tpBtn,tpFrame=createTab("Teleport",2,2)
local function selectTab(i)for idx,t in ipairs(tabs)do t.frame.Visible=(idx==i);t.button.BackgroundColor3=idx==i and Color3.fromRGB(70,70,70)or Color3.fromRGB(50,50,50)end end;selectTab(1);farmBtn.MouseButton1Click:Connect(function()selectTab(1)end);tpBtn.MouseButton1Click:Connect(function()selectTab(2)end)
local function createToggle(parent,label,initial,onToggle)local b=Instance.new("TextButton");b.Size=UDim2.new(1,-8,0,46);b.BackgroundColor3=initial and Color3.fromRGB(50,120,60)or Color3.fromRGB(60,60,60);b.TextColor3=Color3.new(1,1,1);b.TextScaled=true;b.Text=label..(initial and" ON"or" OFF");b.AutoButtonColor=true;b.ZIndex=15;b.Parent=parent;local c=Instance.new("UICorner");c.CornerRadius=UDim.new(0,10);c.Parent=b;local s=Instance.new("UIStroke");s.Thickness=1;s.Transparency=0.8;s.Parent=b;local state=initial;b.MouseButton1Click:Connect(function()state=not state;b.Text=label..(state and" ON"or" OFF");b.BackgroundColor3=state and Color3.fromRGB(50,120,60)or Color3.fromRGB(60,60,60);if onToggle then onToggle(state)end end);return b end
local function createLabel(parent,text)local l=Instance.new("TextLabel");l.Size=UDim2.new(1,-8,0,24);l.BackgroundTransparency=1;l.TextColor3=Color3.fromRGB(210,210,210);l.TextScaled=true;l.Text=text;l.ZIndex=14;l.Parent=parent;return l end
local lblTarget=createLabel(farmFrame,"Alvo: (auto)");local tAuto=createToggle(farmFrame,"Auto Farm (Auto Quest):",false,function(on)autoQuest=on end);local tChest=createToggle(farmFrame,"Auto Chest:",false,function(on)autoChest=on end);local tFruit=createToggle(farmFrame,"Auto Fruit:",false,function(on)autoFruit=on end);local tByLvl=createToggle(farmFrame,"Auto por Level/NextQuest:",true,function(on)autoByLevel=on end);local fruitLabel=createLabel(farmFrame,"Filtro Fruta: nenhum")
local function createTpButton(parent,name,cf)local b=createToggle(parent,"TP: "..name,false,function(_)end);b.MouseButton1Click:Connect(function()teleportToCFrame(cf);pcall(function()StarterGui:SetCore("SendNotification",{Title="VoxSeasHub",Text="TP: "..name,Duration=2})end)end)end
local function refreshSpawnList()for _,child in ipairs(tpFrame:GetChildren())do if child:IsA("TextButton")or child:IsA("TextLabel")then child:Destroy()end end;if not spawnPointsRoot then createLabel(tpFrame,"SpawnPoints não encontrados");return end;for _,d in ipairs(spawnPointsRoot:GetDescendants())do local part=d:IsA("BasePart")and d or d:FindFirstChildWhichIsA("BasePart");if part then createTpButton(tpFrame,d.Name,part.CFrame)end end end;refreshSpawnList()
local open=false;local function openWindow()if open then return end;open=true;mainFrame.Visible=true;mainFrame.Size=UDim2.new(0,10,0,10);mainFrame.BackgroundTransparency=1;TweenService:Create(mainFrame,TweenInfo.new(0.18,Enum.EasingStyle.Quad,Enum.EasingDirection.Out),{Size=UDim2.new(0,300,0,360),BackgroundTransparency=0.25}):Play()end
local function closeWindow()if not open then return end;open=false;local tw=TweenService:Create(mainFrame,TweenInfo.new(0.15,Enum.EasingStyle.Quad,Enum.EasingDirection.In),{Size=UDim2.new(0,10,0,10),BackgroundTransparency=1});tw:Play();tw.Completed:Wait();mainFrame.Visible=false end
menuBtn.MouseButton1Click:Connect(function()if open then closeWindow()else openWindow()end end);closeBtn.MouseButton1Click:Connect(closeWindow)
do local dragging=false;local dragStart;local startPos;header.InputBegan:Connect(function(input)if input.UserInputType==Enum.UserInputType.MouseButton1 or input.UserInputType==Enum.UserInputType.Touch then dragging=true;dragStart=input.Position;startPos=mainFrame.Position;input.Changed:Connect(function()if input.UserInputState==Enum.UserInputState.End then dragging=false end end)end end);header.InputChanged:Connect(function(input)if dragging and(input.UserInputType==Enum.UserInputType.MouseMovement or input.UserInputType==Enum.UserInputType.Touch)then local delta=input.Position-dragStart;mainFrame.Position=UDim2.new(startPos.X.Scale,startPos.X.Offset+delta.X,startPos.Y.Scale,startPos.Y.Offset+delta.Y)end end)end
local lastRefresh=0;RunService.RenderStepped:Connect(function()if mainFrame.Visible and(tick()-lastRefresh)>6 then refreshRoots();refreshSpawnList();lastRefresh=tick()end;lblTarget.Text=("Alvo: %s | Mob: %s"):format(questPattern or"?",enemyBaseName or"?")end)
_G.VoxSeasHubAPI={setQuestPattern=function(p)questPattern=tostring(p or "")end,setEnemyBaseName=function(n)enemyBaseName=tostring(n or "")end,setFruitFilter=function(f)fruitNameFilter=f or nil;fruitLabel.Text="Filtro Fruta: "..(fruitNameFilter or"nenhum")end,toggleAutoQuest=function(on)autoQuest=on;tAuto.Text="Auto Farm (Auto Quest): "..(on and" ON"or" OFF");tAuto.BackgroundColor3=on and Color3.fromRGB(50,120,60)or Color3.fromRGB(60,60,60)end,toggleAutoChest=function(on)autoChest=on;tChest.Text="Auto Chest: "..(on and" ON"or" OFF");tChest.BackgroundColor3=on and Color3.fromRGB(50,120,60)or Color3.fromRGB(60,60,60)end,toggleAutoFruit=function(on)autoFruit=on;tFruit.Text="Auto Fruit: "..(on and" ON"or" OFF");tFruit.BackgroundColor3=on and Color3.fromRGB(50,120,60)or Color3.fromRGB(60,60,60)end,toggleAutoByLevel=function(on)autoByLevel=on;tByLvl.Text="Auto por Level/NextQuest: "..(on and" ON"or" OFF");tByLvl.BackgroundColor3=on and Color3.fromRGB(50,120,60)or Color3.fromRGB(60,60,60)end,refreshSpawns=function()refreshRoots();refreshSpawnList()end}
task.delay(0.1,openWindow);print("[VoxSeasHub] carregado. GUI ativa. Toque no ☰.")
